[app.metadata]
title = "research_elastic_search"
description = "Simple application for testing elastic search capabilities."

[tool.commitizen]
version = "0.2.0"

[tool.kedro]
package_name = "pipelines"
project_name = "pipelines"
project_version = "0.18.0"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120
known_third_party = "kedro"

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = """
--cov-report term-missing \
--cov src/ -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
